name:                htask
version:             0.1.0.0
github:              "palf/htask"
license:             BSD3
author:              "Jack Palfrey"
maintainer:          "jack.palf@gmail.com"
copyright:           "2018 Jack Palfrey"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on Github at <https://github.com/palf/htask#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- conduit
- conduit-combinators
- containers
- mtl
- operational
- optparse-applicative
- random
- text
- pretty
- pretty-show
- tagged
- time
- transformers
- uuid

library:
  source-dirs: lib

executables:
  htask-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htask

tests:
  htask-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htask
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
    - HUnit
