---
kind: pipeline
type: docker
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --recursive --remote

- name: hello
  image: haskell
  commands:
  - ls

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: deploy_webhook
