---
kind: pipeline
type: docker
name: default

steps:
- name: submodules
  image: plugins/git
  recursive: true

- name: build
  image: fpco/stack-build:lts-13.10
  commands:
  - stack build htask-cli

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: deploy_webhook
