---
kind: pipeline
type: docker
name: default

steps:
- name: submodules
  image: plugins/git
  recursive: true

- name: build
  image: localhost:5000/leadpixel/htask-build
  commands:
  - stack test --pedantic
  - stack build --pedantic htask-cli

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: deploy_webhook
