steps:
  - module_header:
      indent: 2
      sort: true
      separate_lists: true
      break_where: single
      open_bracket: next_line

  - records:
      equals: "indent 2"
      first_field: "indent 0"
      field_comment: 2
      deriving: 2
      via: "same_line"
      sort_deriving: true
      break_enums: false

  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always

  - imports:
      align: global
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false
      post_qualify: false
      group_imports: false
      group_rules:
        - match: ".*"
          sub_group: "^[^.]+"

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  - trailing_whitespace: {}

columns: 80

newline: native

cabal: true
