resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/13.yaml

packages:
  - ./packages/provider

  - ./packages/event-core
  - ./packages/event-backend-file
  - ./packages/event-backend-memory

  - ./packages/htask-core
  - ./packages/htask-cli
