resolver: lts-16.8

packages:
  - ./packages/core
  - ./packages/cli

extra-deps:
  - git: https://gitea.leadpixel.org/leadpixel/event-source
    commit: 783822b447c43f0a1fe322c6607952d08a81b6c1
    subdirs:
      - packages/core
      - packages/backends/file
      - packages/backends/memory

  - git: https://gitea.leadpixel.org/leadpixel/provider
    commit: b6c6b35b66b7b9b4fa96d4bd69177927b8709a75
    subdirs:
      - packages/provider
