resolver: lts-13.10

packages:
  - ./packages/htask-lib
  - ./packages/htask-bin
  - ./packages/htask-cli

extra-deps:
  - git: /home/palf/projects/leadpixel/events
    commit: 3837071abcc9ede1a75f5934cf0acff697fb7bec
    subdirs:
    - packages/effects
    - packages/events
    - packages/event-backends/memory
    - packages/event-backends/file
