resolver: lts-16.8

packages:
  - ./packages/core
  - ./packages/cli

extra-deps:
  - git: https://gitea.leadpixel.org/leadpixel/event-source
    commit: 5f40a0d0c7236df6095da1842b730b46233c4656
    subdirs:
      - packages/core
      - packages/backends/file
      - packages/backends/memory

  - git: https://gitea.leadpixel.org/leadpixel/provider
    commit: 01a8f6d8d23310ae487f226cba69978135c24ac6
    subdirs:
      - packages/provider
