resolver: lts-13.10

packages:
  - ./packages/htask-lib
  - ./packages/htask-bin

extra-deps:
  - git: /home/palf/projects/leadpixel/events
    commit: e7038770646b025a141b8c25e67e2e325d7f8243
    subdirs:
    - packages/event
    - packages/event-backends/file
