resolver: lts-13.10

packages:
  - ./packages/htask-lib
  - ./packages/htask-bin

extra-deps:
  - git: /home/palf/projects/leadpixel/events
    commit: 3f9779a88caeb791671d02cdec636f6c5ea5014d
    subdirs:
    - packages/event
    - packages/event-backends/file
