resolver: lts-13.10

packages:
  - ./packages/htask-lib
  - ./packages/htask-bin

extra-deps:
  - git: /home/palf/projects/leadpixel/events
    commit: 0c26aae064f416527605de178948610759e34e3a
    subdirs:
    - packages/effects
    - packages/events
    - packages/event-backends/file
