resolver: lts-16.8

packages:
  - ./packages/core
  - ./packages/cli

extra-deps:
  - git: git@gitea.leadpixel.org:leadpixel/event-source
    commit: e2ae0a7118575bb80e7dc8c128819ce1ab696dc9
    subdirs:
      - packages/core
      - packages/backends/file
      - packages/backends/memory

  - git: git@gitea.leadpixel.org:leadpixel/provider
    commit: e880c45883d0a39ffc536b8781dd01632a5bdef4
    subdirs:
      - packages/provider
