resolver: lts-13.10

packages:
  - ./packages/core
  - ./packages/cli

  - ./modules/events/packages/effects
  - ./modules/events/packages/events
  - ./modules/events/packages/event-backends/memory
  - ./modules/events/packages/event-backends/file
  - ./modules/events/packages/event-backends/sqlite
