name:                event
version:             0.1.0.0
github:              "palf/htask"
license:             BSD3
author:              "Jack Palfrey"
maintainer:          "jack.palf@gmail.com"
copyright:           "2018 Jack Palfrey"

description:         Please see the README on Github at <https://github.com/palf/htask#readme>

ghc-options: -Wall

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- conduit
- conduit-combinators
- mtl
- random
- resourcet
- time
- transformers
- uuid

library:
  source-dirs: lib
  exposed-modules: Event
