_common/legal: !include "../legal.yaml"

name:                htask-lib
version:             0.2.0.0

<<: *legal

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: lib
  exposed-modules:
    - HTask.Core.API
    - HTask.Core.Task
    - HTask.Core.TaskContainer
    - HTask.Core.TaskEvent
    - HTask.Core.Replay
  dependencies:
    - aeson
    - conduit-combinators
    - leadpixel-events
    - leadpixel-provider
    - mtl
    - tagged
    - text
    - time
    - transformers
    - uuid

tests:
  htask-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - aeson
      - bytestring
      - containers
      - event-backend-memory
      - htask-lib
      - leadpixel-events
      - leadpixel-provider
      - mtl
      - quickcheck-instances
      - tagged
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - time
      - transformers
      - uuid
