_common/legal: !include "../legal.yaml"

name:                htask-cli
version:             0.2.0.0

<<: *legal

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5

executables:
  htask:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - MonadRandom
      - event-backend-file
      - htask-lib
      - leadpixel-events
      - leadpixel-provider
      - mtl
      - optparse-applicative
      - time
      - transformers
      - monads-tf
      - tagged
      - text
      - unliftio-core
      - uuid
