name:                htask-bin
version:             0.1.0.0
github:              "palf/htask"
license:             BSD3
author:              "Jack Palfrey"
maintainer:          "jack.palf@gmail.com"
copyright:           "2018 Jack Palfrey"

description:         Please see the README on Github at <https://github.com/palf/htask#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- conduit
- utf8-string
- conduit-combinators
- containers
- mtl
- operational
- optparse-applicative
- pretty
- pretty-show
- random
- tagged
- text
- time
- transformers
- uuid

executables:
  htask:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htask-lib

tests:
  htask-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htask-lib
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
    - HUnit
