name:                htask-bin
version:             0.1.0.0
github:              "palf/htask"
license:             BSD3
author:              "Jack Palfrey"
maintainer:          "jack.palf@gmail.com"
copyright:           "2018 Jack Palfrey"

description:         Please see the README on Github at <https://github.com/palf/htask#readme>

ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N

dependencies:
- base >= 4.7 && < 5
- aeson
- event
- event-backend-file
- unliftio-core
- mtl
- optparse-applicative
- tagged
- text
- transformers
- uuid

executables:
  htask:
    main:                Main.hs
    source-dirs:         src
    dependencies:
    - htask-lib
